version: '3.9'

services:
  untis-db:
    container_name: untis-db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/Untis-Clone/data:/usr/db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=untis-db