spring:
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'
  profiles:
    active: 'dev'

server:
  tomcat:
    max-swallow-size: '100MB'

untis:
  admin:
    secret: 'KeqAKyPZ8g4ckHjcpwrC4GZrCTntXkHnTLfMcUhB4Sztvc0bhxMT9JJN0vhyyQdYr9ifAB8LmCq84HxTJvMfncJHtH623qhmNf5rqYtW5rut1pzd2CMFwGwz2ey9vw11jKEbXG5UmVqWqLc0gYVT0i3rmB98D64DbHJYQvgTK1nTY8N8irpUpdSEg8rJWvVrBvwTKSVCXXitbY68QmM9wbSzNYuFbQL1MkcaM1j94202Mm5SwgUx8b5qkMk8Ud8SgSnB4TnMbbMVr5hdCKqvdKZNZYLByD4y3MGVWT9GL7JapX4c2QcV07FhCJyVM0tGf3Q5AnMkGYNT3WvVxVxLMaywBBTuMCpQYuSEHay5YTzPR2yPa5MJFqkEpmPWbKETX8e2PYY2FvMZxyeWTCZbJECJE7VH4ErZrhY8pqjaYmFdqH7XCvgZ4FgqKV19qu0pimEQD1C9jDKkmb1UinndnXLMt9K0trMK4UDxrimu5pytrFgKYiPjmgx3ERFAwnuu1FEe43rbauXBMNnZv5vScUqbyQUH9947hzzbKjbZg90x3eNhHngpcUiCGLL1en5hgyVfY5EWdS9Umyu026YBcV91krDVuQ6utFNTHSTcUBT7yG3Cui3xkWQP1wP0edeFDJtyBwA5ezXXwr08NRqpqrbBpBQWRn64tjNNCAUiV2BS7c1D3dS0W5x7pxS2BaeC4hqfYxyteyWrxSdNFXmLfVxc3mLmjq0y6ZyGyrR8zF0QKybABWB9RRYXW2ZGDrtmXkAcZnKmCde6q6hxS38FrRRrAD3QqaJpqFGf3cPGFTmZdmbntPfGhqyxDmg4DP0TpAUgfCQCpU037g6qMWaL70ESNcSaz2CfTa24F0tuzcHR4UBS1F8MukFAtxrGyMuhq3LY'
  auth:
    jwt:
      secret: '96c912af-7cdb-400f-adc6-d525e2370b4e'
      expiration: '3600000'
  io:
    attachments: './attachments'